spring:
  application:
    name: form

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/newDb
    username: root
    password: Rakhi_root6
    driver-class-name: com.mysql.cj.jdbc.Driver
                                  
  security:
    user:
      name: "user"
      password: "pass"
